image:
  file: .gitpod.Dockerfile
tasks:
  - command: echo ""
  - init: npm install
    command: cd services/website && npm run dev
ports:
  - port: 3000
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 10000
    onOpen: ignore

vscode:
  extensions:
    - bradlc.vscode-tailwindcss@0.5.4:JBo46wRidL8+LjxbN3OTyA==
