image:
  file: .gitpod.Dockerfile
tasks:
  - command: echo ""
  - init: npm install
    command: cd services/website && npm run dev
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 10000
    onOpen: ignore
