steps:
  # ====================
  # Setup
  # ====================
  - id: "setup-1"
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-audit"]
    waitFor: ["-"] # The "-" indicates that this step begins immediately.
  - id: "setup-2"
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "bootstrap"]
    waitFor: ["setup-1"]
  # ====================
  # Deploy website
  # ====================
  - id: "deploy-website-1"
    name: "gcr.io/$PROJECT_ID/gcp-deployment"
    args: ["run", "deploy"]
    dir: "services/website"
    env:
    - 'DEPLOYMENT_ENV=$_DEPLOYMENT_ENV'
    - 'DEPLOYMENT_VERSION=$COMMIT_SHA'
    - 'FIREBASE_DEPLOY_TOKEN=$_FIREBASE_DEPLOY_TOKEN'
    waitFor: ["setup-2"]