steps:
  # ====================
  # Setup
  # ====================
  - id: "setup-1"
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-audit"]
    waitFor: ["-"] # The "-" indicates that this step begins immediately.
  - id: "setup-2"
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "bootstrap"]
    waitFor: ["setup-1"]
  # ====================
  # Deploy
  # ====================
  - id: "deploy-1"
    name: "gcr.io/$PROJECT_ID/gcp-deployment"
    args: ["run", "deploy"]
    env:
    - 'DEPLOYMENT_VERSION=$COMMIT_SHA'
    - 'FIREBASE_DEPLOY_TOKEN=$_FIREBASE_DEPLOY_TOKEN'
    - 'GHOST_DB_CONNETION_NAME=$_GHOST_DB_CONNETION_NAME'
    - 'GHOST_DB_CONNETION_USER=$_GHOST_DB_CONNETION_USER'
    - 'GHOST_DB_CONNETION_PASSWORD=$_GHOST_DB_CONNETION_PASSWORD'
    waitFor: ["setup-3"]