name: services/website - deployment

on: deployment

jobs:
  test_lighthouse:
    name: Test Lighthouse
    # if: github.event.state == "success"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit Vercel preview URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ github.event.environment_url }}
          budgetPath: ./services/website/.config/lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
  test_e2e:
    name: Test end-to-end
    if: github.event.state == "success"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          config: baseUrl=${{ github.event.environment_url }}
          install: false # We test a live preview URL, no need to install packages
          working-directory: services/website
  test_a11y:
    name: Test a11y
    if: github.event.state == "success"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test a11y
        working-directory: services/website
        run: |
          npx pa11y-ci --config .config/pa11yci.json --sitemap ${{ github.event.environment_url }}/sitemap.xml --sitemap-find https://www.mikenikles.com --sitemap-replace ${{ github.event.environment_url }}
